# Generated by Django 5.1.6 on 2025-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=50)),
                ('hard', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='E_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=50)),
                ('model_divice', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('product_year', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('model_device', models.CharField(max_length=15)),
            ],
        ),
    ]
